paths:
  /api/products:
    post:
      summary: Create a new product
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productCode
                - productName
                - rate
                - gst
                - unit
                - crate
              properties:
                productCode:
                  type: string
                  description: Unique product code
                productName:
                  type: string
                  description: Product name
                rate:
                  type: number
                  description: Product rate
                gst:
                  type: number
                  description: GST percentage
                unit:
                  type: string
                  description: Unit of measurement
                crate:
                  type: integer
                  description: Items per crate
      responses:
        '201':
          description: Product created successfully
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
    get:
      summary: Get all products
      tags: [Products]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Products retrieved successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error

  /api/products/distributor:
    get:
      summary: Get all products with prices for distributor
      tags: [Products]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Products with prices retrieved successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error

  /api/products/{id}:
    get:
      summary: Get product by ID
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product ID
      responses:
        '200':
          description: Product retrieved successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Product not found
        '500':
          description: Server error
    put:
      summary: Update product by ID
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productCode:
                  type: string
                productName:
                  type: string
                rate:
                  type: number
                gst:
                  type: number
                unit:
                  type: string
                crate:
                  type: integer
      responses:
        '200':
          description: Product updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Product not found
        '500':
          description: Server error
    delete:
      summary: Delete product by ID
      tags: [Products]
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product ID
      responses:
        '200':
          description: Product deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Product not found
        '500':
          description: Server error
